<?php require_once './app/views/templates/layout/header.phtml'; ?>

<main class="container py-5">

    <section class="product-section d-flex justify-content-center">

        <div class="item-card">



            <?php if (!empty($perfume->imagen)): ?>

               <img src="/PerfumeTPE/<?= $perfume->imagen ?>"alt="<?= htmlspecialchars($perfume->nombre) ?>"
>
            <?php else: ?>
                <p>No hay imagen cargada.</p>
            <?php endif; ?>

            <h2>
                <?= htmlspecialchars($perfume->nombre) ?>
            </h2>

            <div>

                <p>
                    <strong>Nota olfativa:</strong> 
                    <span><?= htmlspecialchars($perfume->nota) ?></span>
                </p>

                <p>
                    <strong>Variante:</strong> 
                    <span><?= htmlspecialchars($perfume->tipo_variante) ?></span>
                </p>

                <p>
                    <strong>Precio:</strong> 
                    <span>$<?= htmlspecialchars($perfume->precio) ?></span>
                </p>

            </div>

            <div>
                <a href="listaPerfumes" class="btn"> Volver al catálogo</a>
            </div>

        </div>
    </section>
</main>

<?php require_once './app/views/templates/layout/footer.phtml'; ?>