<?php require 'app/views/templates/layout/header.phtml' ?>

<main class="container mt-5">
    <h1 class="mb-4">
        Editando Perfume: <?= htmlspecialchars($perfume->tipo_variante) ?>
    </h1>

    <form 
        action="update-perfume" 
        method="POST"
        enctype="multipart/form-data"
    >

        
        <input type="hidden" name="id" value="<?= $perfume->id ?>">

        <div class="mb-3">
            <label for="tipo_variante" class="form-label">
                Tipo / Variante
            </label>

            <input 
                type="text" 
                class="form-control" 
                name="tipo_variante" 
                id="tipo_variante"
                value="<?= htmlspecialchars($perfume->tipo_variante) ?>"
                required
            >
        </div>

        <div class="mb-3">
            <label for="origen" class="form-label">
                Nombre
            </label>

            <input 
                type="text" 
                class="form-control" 
                name="nombre" 
                id="origen" 
                value="<?= htmlspecialchars($perfume->nombre) ?>" 
                required
            >
        </div>

        <div class="mb-3">
            <label for="acabados_comunes" class="form-label">
                Nota
            </label>

            <input 
                type="text" 
                class="form-control" 
                name="nota" 
                id="acabados_comunes" 
                value="<?= htmlspecialchars($perfume->nota) ?>"
            >
        </div>

        <div class="mb-3">
            <label for="uso_recomendado" class="form-label">
                Precio
            </label>

            <input 
                type="text" 
                class="form-control" 
                name="precio" 
                id="uso_recomendado" 
                value="<?= htmlspecialchars($perfume->precio) ?>"
            >
        </div>

        <div class="mb-3">

            <label class="form-label">
                Imagen Actual
            </label>
            <br>
            <?php if (!empty($perfume->imagen)): ?>
                <img 
                    src="<?= BASE_URL . $perfume->imagen ?>"
                    alt="<?= htmlspecialchars($perfume->nombre) ?>"
                    style="width:200px; border-radius:12px; margin-bottom:10px;"
                >

            <?php else: ?>
                <p>No hay imagen cargada.</p>
            <?php endif; ?>
        </div>

        <div class="mb-3">
            <label class="form-label">
                Nueva Imagen
            </label>
            <input  type="file" class="form-control" name="imagen">
        </div>

        <div class="mb-3">

            <label for="id_categoria" class="form-label">
                Categoría
            </label>

            <select class="form-select" name="id_categoria" id="id_categoria"  required>

                <?php foreach ($categorias as $categoria): ?>

                    <option 
                        value="<?= $categoria->id ?>" 
                        <?= ($categoria->id == $perfume->id_categoria) ? 'selected' : '' ?>
                    >
                        <?= htmlspecialchars($categoria->nombre) ?>
                    </option>

                <?php endforeach; ?>

            </select>
        </div>

        <button type="submit" class="btn btn-primary">
            Actualizar Perfume
        </button>

        <a href="panel_de_control" class="btn btn-secondary">
            Cancelar
        </a>

    </form>
</main>

<?php require 'app/views/templates/layout/footer.phtml' ?>