<?php require 'app/views/templates/layout/header.phtml' ?>

<section class="hero">
    <div class="hero-content">
        <h1>BUENAS CHAVALES</h1>
        <p>Descubre nuestra amplia variedad de perfumes de Amaredeado, Citrico y Oriental  para oler con con estilo y calidad.</p>
        <a href="listaPerfumes" class="btn">Ver Productos</a>
    </div>
</section>

<?php require 'app/views/templates/layout/footer.phtml' ?>