<?php require 'app/views/templates/layout/header.phtml' ?>
<main class="container py-5">
    <section id="catalogo" class="product-section">
        <h2 class="mb-3">
            <?php echo isset($categoria_nombre) ? 'Perfumes de ' . htmlspecialchars($categoria_nombre) : 'Catálogo de Perfumes'; ?>
        </h2>
        <p class="section-description">Explora nuestra selección premium de perfumes, incluyendo variedades
            específicas de Floral, Arabe y Citrico.</p>

        <?php if (empty($perfumes)): ?>
            <div class="alert alert-info text-center" role="alert">
                No hay pisos cargados en esta categoría.
            </div>
        <?php else: ?>
            <div class="card-grid">
                <?php foreach ($perfumes as $perfumes): ?>
                    <div class="item-card">
                        <div class="item-card-content">
                            <h3><?= htmlspecialchars($perfumes->tipo_variante) ?></h3>
                            <p><strong>Categoría:</strong> <?= htmlspecialchars($perfumes->categoria) ?></p>
                            <p><strong>Nombre:</strong> <?= htmlspecialchars($perfumes->nombre) ?></p>
                            <p><strong>Nota:</strong> <?= htmlspecialchars($perfumes->nota) ?></p>
                            <p><strong>Precio:</strong> $<?= htmlspecialchars($perfumes->precio)?></p>
                        </div>
                        <div class="item-card-footer">
                            <a href="detalle_perfume/<?= $perfumes->id ?>">Ver más detalles →</a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </section>
</main>

<?php require 'app/views/templates/layout/footer.phtml' ?>